#!/bin/sh

# fail fast
set -o errexit
set -o pipefail

slug=$(heroku build https://github.com/ddollar/releases.git -p)

# save cloud and switch to the standard cloud
cloud=$(heroku cloud)
heroku cloud standard

# release to standard staging using standard production
env RELEASE_HOST=https://releases-production.herokuapp.com heroku release $slug -a releases-staging

# release to standard staging again using itself to make sure it's working
env RELEASE_HOST=https://releases-staging.herokuapp.com heroku release $slug -a releases-staging

# release to standard production using standard staging
heroku cloud standard
env RELEASE_HOST=https://releases-staging.herokuapp.com heroku release $slug -a releases-production

# release to shadow staging and production using standard production
heroku cloud shadow
env RELEASE_HOST=https://releases-production.herokuapp.com heroku release $slug -a releases-staging
env RELEASE_HOST=https://releases-production.herokuapp.com heroku release $slug -a releases-production

# restore old cloud
heroku cloud $cloud
