#!/bin/sh

# fail fast
set -o errexit
set -o pipefail

# compile a slug from git
slug=$(heroku build https://github.com/ddollar/releases.git -p)

# release to standard staging using standard production
env RELEASES_HOST=https://releases-production.herokuapp.com heroku release $slug -a releases-staging

# release to standard staging again using itself to make sure it's working
env RELEASES_HOST=https://releases-staging.herokuapp.com heroku release $slug -a releases-staging

# release to standard production using standard staging
env RELEASES_HOST=https://releases-staging.herokuapp.com heroku release $slug -a releases-production
